### ISSUE TITLE
Fail to build on ubuntu 18.04

### ISSUE THREAD

**Issue by prudhomm** [asciidoctor/asciidoctor#3904]
cpr fails to build on 18.04 due to a missing enum

it is strange that it is not detected by github actions on ubuntu 18.04
I installed `apt install libcurl4-openssl-dev` and it seems that github virtual-environments
could it be that `curl` is fetched in all the actions and so such an issue is not detected ? 
In my case I have to use the system curl

here is the error
```
/build/feelpp-0.109.0~alpha.1/feelpp/contrib/cpr/cpr/session.cpp:168:55: error: use of undeclared identifier 'CURLAUTH_BEARER'; did you mean 'CURLOPT_HEADER'?
--
  | curl_easy_setopt(curl_->handle, CURLOPT_HTTPAUTH, CURLAUTH_BEARER);
  | ^~~~~~~~~~~~~~~
  | CURLOPT_HEADER
  | /usr/include/x86_64-linux-gnu/curl/curl.h:2744:72: note: expanded from macro 'curl_easy_setopt'
  | #define curl_easy_setopt(handle,opt,param) curl_easy_setopt(handle,opt,param)
  | ^
  | /usr/include/x86_64-linux-gnu/curl/curl.h:1059:3: note: 'CURLOPT_HEADER' declared here
  | CINIT(HEADER, LONG, 42),       /* throw the header out too */
  | ^
  | /usr/include/x86_64-linux-gnu/curl/curl.h:896:24: note: expanded from macro 'CINIT'
  | #define CINIT(na,t,nu) CURLOPT_ ## na = CURLOPTTYPE_ ## t + nu
  | ^
  | <scratch space>:349:1: note: expanded from here
  | CURLOPT_HEADER
  | ^
```

**Comment by abelsromero** [comment]
Are you sure this is the right repo?

**Comment by prudhomm** [comment]
Oops
