### ISSUE TITLE
Asciidoctor 2.x gem doesn't declare minimal Ruby version

### ISSUE THREAD

**Issue by ericzolf** [asciidoctor/asciidoctor#4082]
https://rubygems.org/gems/asciidoctor/ states that any version of ruby will work but actually at least version 1.8 doesn't work. Per se this isn't an issue but that means that a too high version is installed where a lower version might work. Ruby 2.0 works BTW.

I noticed because I need asciidoctor for my (Python) build process, and the manylinux 2010 image contains ruby 1.8:

```
gem install asciidoctor
ERROR:  While generating documentation for asciidoctor-2.0.15
... MESSAGE:   Unhandled special: Special: type=17, text="<!--1-->"
... RDOC args: --ri --op /usr/lib/ruby/gems/1.8/doc/asciidoctor-2.0.15/ri --quiet lib --title asciidoctor-2.0.15 Documentation
(continuing with the rest of the installation)
Successfully installed asciidoctor-2.0.15
1 gem installed
Installing ri documentation for asciidoctor-2.0.15...
Installing RDoc documentation for asciidoctor-2.0.15...
[...]
  executing ('asciidoctor -b manpage -a revdate="{date}" -a revnumber="{ver}" -o {outfile} {infile}', ('docs', 'rdiff-backup.1.adoc'), ('build', 'rdiff-backup.1'))
  /usr/lib/ruby/gems/1.8/gems/asciidoctor-2.0.15/bin/asciidoctor:4: undefined local variable or method `__dir__' for main:Object (NameError)
  	from /usr/bin/asciidoctor:19:in `load'
  	from /usr/bin/asciidoctor:19
```

The same build process works in manylinux 2014 with Ruby 2.0.

**Comment by mojavelinux** [comment]
I'm not going to declare the minimum version because I don't believe in doing that. I think it wrecks havoc on build systems because RubyGems has no way to override this. This problem is particularly apparent for packagers, who can run into problems trying to install gems even though they have patched the gem to work for the version of Ruby in the OS.

We document the minimum required version in the documentation. See https://docs.asciidoctor.org/asciidoctor/latest/install/supported-platforms/ Asciidoctor requires at least Ruby 2.3.

**Comment by mojavelinux** [comment]
FYI, Asciidoctor hasn't supported Ruby 1.8 for a very long time. And we have been clear about this in the README and docs.

**Comment by ericzolf** [comment]
My point is that the gem isn't packaged so that it appears at the technical level.

**Comment by mojavelinux** [comment]
I've stated my reason for not doing so. If RubyGems were to allow it to be overridden, I would change my position.

**Comment by ericzolf** [comment]
Your first answer disappeared in my SPAM folder and I noticed only your 2nd one. Now, I got your point. Sorry for the noise.
